layout_spectrum: 1
color:
  saturation: 0.3286112
  lightness: 0.1156219
  brandStrength: 0.5243938
  brandColors:
    - '#383A42'
    - '#90645D'
    - '#A3A2A4'
    - '#FAFFFF'
    - '#3A3604'
  rhythmicContrast: 0.9623567
typography_spectrum: 0.3924731
name: stiefel.io
